spring:
  application:
    name: blog-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: s.nbfg
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml