// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/proto/BusinessPayload.proto
// Protobuf Java Version: 4.28.3

package com.example.datasourceservice.protobuf;

public interface BusinessPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.datasourceservice.protobuf.BusinessPayload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string order = 2;</code>
   * @return The order.
   */
  java.lang.String getOrder();
  /**
   * <code>string order = 2;</code>
   * @return The bytes for order.
   */
  com.google.protobuf.ByteString
      getOrderBytes();

  /**
   * <code>string content = 3;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 3;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
