server:
  port: 8081
logging:
  level:
    org.springframework.web.reactive: DEBUG
spring:
  codec:
    max-in-memory-size: 32MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true