spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        "[globally_quoted_identifiers]": true
        "[globally_quoted_identifiers_skip_column_definitions]": true