// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/proto/BusinessPayload.proto
// Protobuf Java Version: 4.28.3

package com.example.businessclientservice.protobuf;

public final class BusinessPayloadOuterClass {
  private BusinessPayloadOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      BusinessPayloadOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_businessclientservice_protobuf_BusinessPayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_businessclientservice_protobuf_BusinessPayload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.src/main/resources/proto/BusinessPaylo" +
      "ad.proto\022*com.example.businessclientserv" +
      "ice.protobuf\"?\n\017BusinessPayload\022\014\n\004name\030" +
      "\001 \001(\t\022\r\n\005order\030\002 \001(\t\022\017\n\007content\030\003 \001(\tB.\n" +
      "*com.example.businessclientservice.proto" +
      "bufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_businessclientservice_protobuf_BusinessPayload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_businessclientservice_protobuf_BusinessPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_businessclientservice_protobuf_BusinessPayload_descriptor,
        new java.lang.String[] { "Name", "Order", "Content", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
